# Input - Header
HEADERS   += QExtAction.h
HEADERS 	+= QECBRobotsWindow.h
HEADERS 	+= QLogViewWidget.h
HEADERS 	+= QMessageClient.h
HEADERS 	+= types.h
HEADERS   += ECBCommunicationEvent.h
HEADERS   += ECBCommunicationData.h
HEADERS   += QECBCommunicator.h
HEADERS   += QECBManager.h
HEADERS   += ecb.h
HEADERS   += ecbrobot.h
HEADERS   += ecbagent.h
HEADERS   += QGlobalData.h


# Input - Sources
SOURCES   += QExtAction.cpp
SOURCES 	+= QECBRobotsWindow.cpp
SOURCES 	+= QLogViewWidget.cpp
SOURCES 	+= QMessageClient.cpp
SOURCES   += ECBCommunicationEvent.cpp
SOURCES   += ECBCommunicationData.cpp
SOURCES   += QECBCommunicator.cpp
SOURCES   += QECBManager.cpp
SOURCES   += ecb.cpp
SOURCES   += ecbrobot.cpp
SOURCES   += ecbagent.cpp
SOURCES   += QGlobalData.cpp