######################################################################
# Automatically generated by qmake (2.01a) Mo Jul 28 00:26:04 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui-test.h SphericalRobotGUI.h SphericalRobotSubWidget.h
FORMS += gui-test.ui
SOURCES += main.cpp SphericalRobotGUI.cpp SphericalRobotSubWidget.cpp
