# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

FILES          = main


#CONFIGURATOR   = $(LPZROBOTS)/configurator
#ADDITIONAL_LIBS = -L$(CONFIGURATOR) -lconfigurator -lQtCore -lQtGui -l QtXml