

all:
	g++ -g -Wall -losgShadow -losgText -losgUtil -losgViewer -losgGA -lOpenThreads -losgManipulator -losg -lGL -lGLU -lglut test_georg.cpp lpzviewer.cpp

sync:
	g++ -g -Wall -losgShadow -losgText -losgUtil -losgViewer -losgGA -lOpenThreads -losgManipulator -losg -lGL -lGLU -lglut async_texture_rendering.cpp
