#!/bin/bash

set -e # exit if command fails
if [ $# -le 3 ]; then
   echo "Usage $0 packdir packname version folder [onlysource]"
   echo "    onlysource means that the debian package is not build completetly"
   echo "    this has not influence on the ubuntu packages anyway"
   exit 1
fi 
Packdir=$1
PackName=$2
Version=$3
Folder=$4
OnlySource=$5

pushd `pwd`

ORIGTGZ="${PackName}_${Version}.orig.tar.gz"
if [ -e "$Packdir/${ORIGTGZ}" ]; then
    echo "found $ORIGTGZ";
else
    echo "$ORIGTGZ not found in $Packdir!";
    exit 1;
fi
    
# untar them 
cd "$Packdir"
tar -xzf ${ORIGTGZ}
pushd `pwd`

cd ${Folder}
# first make debian unstable package
if [ -z "$OnlySource" ]; then # full package
    debuild
else
    echo "########## BUILD ONLY SOURCE DEBIAN PACKAGE ########### "
fi
debuild -S 

# copy debian packages
popd
pushd `pwd`
mkdir -p debian-unstable
mv *.diff.gz *.build *.changes *.dsc debian-unstable
cp ${ORIGTGZ} debian-unstable
if [ -z "$OnlySource" ]; then 
  mv *.deb debian-unstable
fi
# make ubuntu packages for launchpad
mkdir -p ubuntu
cd ${Folder}
FIRST=""
for Dist in jaunty karmic lucid maverick; do
    # change changelog for all ubuntu distributions  
    dch --increment -D $Dist "$Dist version"
    # make only source package
    if [ -z "$FIRST" ]; then
        debuild -S -sa
    else
        debuild -S
    fi
    FIRST="no"
done
popd
cp ${ORIGTGZ} ubuntu
mv *.diff.gz *.build *.changes *.dsc ubuntu
popd # return to place where we started
