# subdirectories which contain libraries or binaries needed some of the other project in this tree 
SIMULATIONS= \
	zoo \
	teaching \
	short_circuit \
	sphericalrobot \
	template_onerobot \
	template_schlange \
	template_sphererobot \
	template_component \
        template_cycled_GA_Simulation \
        template_cycledSimulation \
        template_hand \
        template_snakebot \
        template_spiderbot \
        template_tasked_GA_Simulation \
        template_taskedSimulations \
	hurling_snake \
	nimm2_arena \
	robodrom \
	wheelie \
	uwo \
	nimm2_eating\
	nimm2_hebb\
	vierbeiner \
        tests
